name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.2.8', '9.4.7', '9.6.7']
        cabal: ['3.12.1.0']

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-cabal-

    - name: Update package list
      run: cabal update

    - name: Run cabal check
      run: cabal check

    - name: Install HLint
      uses: haskell/actions/hlint-setup@v2
      with:
        version: '3.5'

    - name: Run HLint
      uses: haskell/actions/hlint-run@v2
      with:
        path: '["src/", "test/", "programs/"]'
        fail-on: error

    - name: Build
      run: cabal build all --enable-tests

    - name: Run tests
      run: cabal test all

    - name: Generate documentation
      run: cabal haddock
      if: matrix.ghc == '9.4.7' && matrix.os == 'ubuntu-latest' 